{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iperf-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iperf-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  selector:
    matchLabels:
      {{- include "iperf-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iperf-operator.fullname" . }}-exporters
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iperf-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf-exporter
      app.kubernetes.io/component: server
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      honorLabels: true
{{- end }}
