apiVersion: netperf.iperfexporter.io/v1alpha1
kind: LinkMeasurement
metadata:
  name: tcp-demo
  namespace: iperf-exporter-demo
spec:
  profileRef: tcp-quality-continuous
  source:
    cluster: cluster-a
    nodeName: iperf-demo-worker
  destination:
    cluster: cluster-a
    nodeName: iperf-demo-worker2
  directions:
    - sourceToDestination
    - destinationToSource
  networkModes:
    - host
    - pod
    - service
  execution:
    mode: continuous
