apiVersion: netperf.iperfexporter.io/v1
kind: MeasurementProfile
metadata:
  name: tcp-throughput-probe
  namespace: iperf-exporter-demo
spec:
  protocol: tcp
  exporter:
    port: 5003
    bindPort: 9870
    interval: 1
    len: 8192
    metricTTL: 120
    clientBandwidth: 200M
    clientDuration: 180
    clientAdditionalParams: --trip-times
    serverAdditionalParams: --histograms=100u,20
    pathTraceTTL: 60
    pathTraceMaxHops: 8
    pathTraceTimeout: 5
