apiVersion: netperf.iperfexporter.io/v1alpha1
kind: MeasurementProfile
metadata:
  name: udp-quality-continuous
  namespace: iperf-exporter-demo
spec:
  protocol: udp
  exporter:
    port: 5002
    bindPort: 9869
    interval: 1
    len: 1280
    metricTTL: 120
    clientBandwidth: 2M
    clientDuration: 315360000
    pathTraceTTL: 60
    pathTraceMaxHops: 8
    pathTraceTimeout: 5
