apiVersion: netperf.iperfexporter.io/v1
kind: MeasurementProfile
metadata:
  name: udp-quality-periodic
  namespace: iperf-exporter-demo
spec:
  protocol: udp
  exporter:
    port: 5006
    bindPort: 9873
    interval: 1
    len: 1280
    metricTTL: 120
    clientBandwidth: 8M
    clientDuration: 180
    pathTraceTTL: 60
    pathTraceMaxHops: 8
    pathTraceTimeout: 5
