apiVersion: netperf.iperfexporter.io/v1alpha1
kind: RemoteCluster
metadata:
  name: cluster-b
  namespace: iperf-exporter-demo
spec:
  namespace: iperf-exporter-demo
  kubeconfigSecretRef:
    name: cluster-b-kubeconfig
    key: kubeconfig
