apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf-exporter-demo
resources:
  - namespace.yaml
  - measurementprofiles-crd.yaml
  - linkmeasurements-crd.yaml
  - measurementsessions-crd.yaml
  - remoteclusters-crd.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - prometheus-serviceaccount.yaml
  - prometheus-role.yaml
  - prometheus-rolebinding.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml
