apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remoteclusters.netperf.iperfexporter.io
spec:
  group: netperf.iperfexporter.io
  names:
    kind: RemoteCluster
    plural: remoteclusters
    singular: remotecluster
    shortNames:
      - rcluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .spec.namespace
        - name: Phase
          type: string
          jsonPath: .status.phase
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - kubeconfigSecretRef
              properties:
                namespace:
                  type: string
                kubeconfigSecretRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    key:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
