apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iperf-exporter-operator
rules:
  - apiGroups:
      - netperf.iperfexporter.io
    resources:
      - measurementprofiles
      - linkmeasurements
      - measurementsessions
      - remoteclusters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - netperf.iperfexporter.io
    resources:
      - measurementprofiles/status
      - linkmeasurements/status
      - measurementsessions/status
      - remoteclusters/status
      - measurementprofiles/finalizers
      - linkmeasurements/finalizers
      - measurementsessions/finalizers
      - remoteclusters/finalizers
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
