FROM python:3.14-alpine

RUN adduser -H -S -D -u 1000 iperf_operator

WORKDIR /app

COPY requirements-operator.txt ./

# hadolint ignore=DL3013
RUN python -m pip install --no-cache-dir -r requirements-operator.txt

COPY iperf_operator ./iperf_operator

ARG VERSION=dev

USER iperf_operator

LABEL maintainer=loktionovam@gmail.com
LABEL version=${VERSION}

ENV IPERF_OPERATOR_DEFAULT_EXPORTER_IMAGE=loktionovam/iperf_exporter_server:${VERSION} \
    IPERF_OPERATOR_VERSION=${VERSION} \
    PYTHONPATH=/app \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

EXPOSE 9869

ENTRYPOINT ["kopf", "run", "--standalone", "-m", "iperf_operator.controller"]
