---
version: "3.4"

services:
  iperf-exporter-client-to-127-0-0-1:
    image: iperf_exporter_client:v1.0.0
    container_name: iperf-exporter-client-to-127-0-0-1
    network_mode: host
    environment:
      IPERF_EXPORTER_CLIENT_BANDWIDTH: 200K
      IPERF_EXPORTER_CLIENT_PEER: 127.0.0.1
