apiVersion: v1
kind: ServiceAccount
metadata:
  name: iperf-exporter-remote-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iperf-exporter-remote-access
rules:
  - apiGroups: [""]
    resources: [pods, endpoints]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, watch, create, patch, delete]
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [get, list, watch, create, patch, delete]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, watch, create, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iperf-exporter-remote-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iperf-exporter-remote-access
subjects:
  - kind: ServiceAccount
    name: iperf-exporter-remote-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iperf-exporter-remote-node-read
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iperf-exporter-remote-node-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iperf-exporter-remote-node-read
subjects:
  - kind: ServiceAccount
    name: iperf-exporter-remote-access
    namespace: iperf-measurements
