apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iperf-exporter-remote-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iperf-exporter-remote-access
subjects:
  - kind: ServiceAccount
    name: iperf-exporter-remote-access
    namespace: iperf-exporter-demo
