{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iperf-exporter-server.componentName" (dict "root" . "component" "server") }}
  labels:
    {{- include "iperf-exporter-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.config.port }}
      targetPort: iperf
      protocol: {{ .Values.server.config.proto | upper }}
      name: iperf
    - port: {{ .Values.server.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "iperf-exporter-server.componentSelectorLabels" (dict "root" . "component" "server") | nindent 4 }}
{{- end }}
