apiVersion: v1
kind: Service
metadata:
  name: {{ include "iperf-exporter-server.fullname" . }}
  labels:
    {{- include "iperf-exporter-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "iperf-exporter-server.selectorLabels" . | nindent 4 }}
